ProyectoWeb2/config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  resources :usuarios
  resources :products
  resources :sessions
  resources :users do
  collection do
        get 'logout', :action => 'logout'
    end
  end  
  resources :tokens,:only => [:create, :destroy, :update] do
  collection do
      get 'users', :action => 'getUser'
  end
end

end

ProyectoWeb2/app/models/usuario.rb
class Usuario < ActiveRecord::Base

  #attr_accessor :password_hash
  before_save :encrypt_password
  
  #validates_confirmation_of :password_hash
  #validates_presence_of :password_hast, :on => :create
  validates_presence_of :username
  validates_uniqueness_of :username
  
  def encrypt_password
    if password_hast.present?
      self.password_salt = BCrypt::Engine.generate_salt
      self.password_hast = BCrypt::Engine.hash_secret(password_hast, password_salt)
    end
  end

  def self.authenticate(username, password_hast)
  #user = find_by_email(username)
  #if user && user.password_hast == BCrypt::Engine.hash_secret(password_hast, user.password_salt)
    user
  #else
   # nil
  #end
  end

end

ProyectoWeb2/app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update

    usuario = Usuario.authenticate(params[:username], params[:password_hast])  
  
    if usuario

    respond_to do |format|
      #if @usuario.update(usuario_params)
      if @usuario.update(params[:username], params[:password_hast],params[:password_salt], params[:token])
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      #params.require(:usuario).permit(:username, :password_hast, :password_salt, :token)
    end
end

ProyectoWeb2/app/helpers/usuarios_helper.rb
module UsuariosHelper
end

ProyectoWeb2/app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password_hast %><br>
    <%= f.text_field :password_hast %>
  </div>
  <div class="field">
    <%= f.label :password_salt %><br>
    <%= f.text_field :password_salt %>
  </div>
  <div class="field">
    <%= f.label :token %><br>
    <%= f.text_field :token %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

ProyectoWeb2/app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

ProyectoWeb2/app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password hast</th>
      <th>Password salt</th>
      <th>Token</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.username %></td>
        <td><%= usuario.password_hast %></td>
        <td><%= usuario.password_salt %></td>
        <td><%= usuario.token %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

ProyectoWeb2/app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

ProyectoWeb2/app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @usuario.username %>
</p>

<p>
  <strong>Password hast:</strong>
  <%= @usuario.password_hast %>
</p>

<p>
  <strong>Password salt:</strong>
  <%= @usuario.password_salt %>
</p>

<p>
  <strong>Token:</strong>
  <%= @usuario.token %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>